spring:
  application:
    name: frete
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: gabriel
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update